// Generated by CoffeeScript 1.7.1
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.tabs.sendMessage(tab.id, "qrcode");
  });

}).call(this);

//# sourceMappingURL=index.map
